spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/spring-boot-elasticsearch}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:P4ssword!}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
  data:
    elasticsearch:
      repositories:
        enabled: false
  elasticsearch:
    uris:
      - localhost:${ES_PORT:9200}
    username: elastic
    password: ${ELASTIC_PASSWORD:changeme}
  docker:
    compose:
      lifecycle-management: start-only
error:
  handling:
    http-status-in-json-response: true
    exception-logging: NO_LOGGING
    full-stacktrace-http-statuses: 5xx
    log-levels:
      5xx: ERROR
    codes:
      UserUsernameUnique: USER_USERNAME_UNIQUE
      TagNameUnique: TAG_NAME_UNIQUE
springdoc:
  pathsToMatch: /api/**

project:
  elasticsearch:
    ssl-fingerprint-ca: ${ES_SSL:changeme}

logging:
  level:
    org.springframework.data.elasticsearch.client: trace
    org.springframework.data.elasticsearch.core: trace
